import { useEffect, useMemo, useState } from 'react';
import { CheckSquare, Plus, Trash2 } from 'lucide-react';
import { Task, TaskPriority, TaskType } from '../../types';
import { createTask, deleteTask, loadTasks, updateTask } from '../../lib/backendApi';
import { toast } from 'sonner';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';

const newTaskDefaults = {
  title: '',
  description: '',
  type: 'general' as TaskType,
  priority: 'medium' as TaskPriority,
};

export function OwnerTasksPanel() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [draft, setDraft] = useState(newTaskDefaults);

  const refresh = async () => {
    setIsLoading(true);
    try {
      setTasks(await loadTasks());
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Не удалось загрузить задачи');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  const stats = useMemo(
    () => ({
      total: tasks.length,
      todo: tasks.filter((task) => task.status === 'todo').length,
      done: tasks.filter((task) => task.status === 'done').length,
    }),
    [tasks],
  );

  const add = async () => {
    if (!draft.title.trim()) {
      toast.error('Введите название задачи');
      return;
    }
    const now = new Date();
    const optimistic: Task = {
      id: `task-${Date.now()}`,
      title: draft.title.trim(),
      description: draft.description.trim(),
      type: draft.type,
      priority: draft.priority,
      status: 'todo',
      assigneeId: 'owner',
      assigneeName: 'Владелец',
      createdBy: 'owner',
      createdByName: 'Владелец',
      createdAt: now,
      isAutoGenerated: false,
    };
    try {
      const created = await createTask(optimistic);
      setTasks((prev) => [created, ...prev]);
      setIsDialogOpen(false);
      setDraft(newTaskDefaults);
      toast.success('Задача создана');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Не удалось создать задачу');
    }
  };

  const toggleDone = async (task: Task) => {
    const newStatus = task.status === 'done' ? 'todo' : 'done';
    try {
      const updated = await updateTask(task.id, {
        status: newStatus,
        completedAt: newStatus === 'done' ? new Date() : undefined,
      });
      setTasks((prev) => prev.map((item) => (item.id === task.id ? updated : item)));
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Не удалось обновить задачу');
    }
  };

  const remove = async (taskId: string) => {
    if (!window.confirm('Удалить задачу?')) {
      return;
    }
    try {
      await deleteTask(taskId);
      setTasks((prev) => prev.filter((task) => task.id !== taskId));
      toast.success('Задача удалена');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Не удалось удалить задачу');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-[#133C2A] mb-2">Задачи</h1>
          <p className="text-[#133C2A]/60">Операционные задачи владельца</p>
        </div>
        <Button onClick={() => setIsDialogOpen(true)} className="rounded-2xl bg-gradient-to-r from-[#133C2A] to-[#D4AF37]">
          <Plus className="w-4 h-4 mr-2" />
          Новая задача
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="border-none soft-shadow"><CardContent className="p-5"><p className="text-sm text-[#133C2A]/60">Всего</p><p className="text-3xl text-[#133C2A]">{stats.total}</p></CardContent></Card>
        <Card className="border-none soft-shadow"><CardContent className="p-5"><p className="text-sm text-[#133C2A]/60">В работе</p><p className="text-3xl text-[#133C2A]">{stats.todo}</p></CardContent></Card>
        <Card className="border-none soft-shadow"><CardContent className="p-5"><p className="text-sm text-[#133C2A]/60">Выполнено</p><p className="text-3xl text-[#133C2A]">{stats.done}</p></CardContent></Card>
      </div>

      <Card className="border-none soft-shadow">
        <CardHeader><CardTitle className="text-[#133C2A]">Список задач</CardTitle></CardHeader>
        <CardContent className="space-y-3">
          {isLoading ? (
            <p className="text-[#133C2A]/60">Загрузка...</p>
          ) : tasks.length === 0 ? (
            <p className="text-[#133C2A]/60">Задач пока нет</p>
          ) : (
            tasks.map((task) => (
              <div key={task.id} className="rounded-2xl border border-[#133C2A]/10 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="space-y-1">
                    <p className="text-[#133C2A]">{task.title}</p>
                    <p className="text-sm text-[#133C2A]/70">{task.description || 'Без описания'}</p>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className="rounded-xl">{task.type}</Badge>
                      <Badge variant="outline" className="rounded-xl">{task.priority}</Badge>
                      <Badge variant="outline" className="rounded-xl">{task.status === 'done' ? 'Выполнено' : 'В работе'}</Badge>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => void toggleDone(task)} className="rounded-xl">
                      <CheckSquare className="w-4 h-4" />
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => void remove(task.id)} className="rounded-xl">
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            ))
          )}
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="rounded-3xl">
          <DialogHeader><DialogTitle className="text-[#133C2A]">Новая задача</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div className="space-y-1">
              <Label>Название</Label>
              <Input value={draft.title} onChange={(e) => setDraft((prev) => ({ ...prev, title: e.target.value }))} />
            </div>
            <div className="space-y-1">
              <Label>Описание</Label>
              <Textarea value={draft.description} onChange={(e) => setDraft((prev) => ({ ...prev, description: e.target.value }))} />
            </div>
            <div className="space-y-1">
              <Label>Тип</Label>
              <Select value={draft.type} onValueChange={(value: TaskType) => setDraft((prev) => ({ ...prev, type: value }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="general">Общая</SelectItem>
                  <SelectItem value="payment">Оплата</SelectItem>
                  <SelectItem value="student">Ученик</SelectItem>
                  <SelectItem value="schedule">Расписание</SelectItem>
                  <SelectItem value="communication">Коммуникация</SelectItem>
                  <SelectItem value="system">Система</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1">
              <Label>Приоритет</Label>
              <Select value={draft.priority} onValueChange={(value: TaskPriority) => setDraft((prev) => ({ ...prev, priority: value }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Низкий</SelectItem>
                  <SelectItem value="medium">Средний</SelectItem>
                  <SelectItem value="high">Высокий</SelectItem>
                  <SelectItem value="urgent">Срочный</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)} className="rounded-2xl">Отмена</Button>
            <Button onClick={() => void add()} className="rounded-2xl bg-gradient-to-r from-[#133C2A] to-[#D4AF37]">Создать</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
