import { useState } from 'react';
import { Task, TaskPriority, TaskType, User } from '../../types';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { 
  Plus,
  CheckCircle2, 
  Clock, 
  AlertCircle, 
  Circle,
  Calendar,
  User as UserIcon,
  CreditCard,
  GraduationCap,
  CalendarDays,
  MessageSquare,
  FileText,
  Settings,
  ChevronDown,
  Edit,
  Trash2
} from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../ui/dialog';
import { toast } from 'sonner@2.0.3';

interface OwnerTasksProps {
  tasks: Task[];
  user: User;
}

const priorityConfig: Record<TaskPriority, { label: string; color: string; bgColor: string }> = {
  low: { label: 'Низкий', color: 'text-blue-600', bgColor: 'bg-blue-50 border-blue-200' },
  medium: { label: 'Средний', color: 'text-yellow-600', bgColor: 'bg-yellow-50 border-yellow-200' },
  high: { label: 'Высокий', color: 'text-orange-600', bgColor: 'bg-orange-50 border-orange-200' },
  urgent: { label: 'Срочно', color: 'text-red-600', bgColor: 'bg-red-50 border-red-200' },
};

const typeConfig: Record<TaskType, { label: string; icon: any }> = {
  payment: { label: 'Оплата', icon: CreditCard },
  student: { label: 'Ученики', icon: GraduationCap },
  schedule: { label: 'Расписание', icon: CalendarDays },
  communication: { label: 'Коммуникация', icon: MessageSquare },
  general: { label: 'Общее', icon: FileText },
  system: { label: 'Система', icon: Settings },
};

export function OwnerTasks({ tasks, user }: OwnerTasksProps) {
  const [filter, setFilter] = useState<'all' | 'active' | 'completed'>('all');
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [detailsOpen, setDetailsOpen] = useState(false);

  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    type: 'general' as TaskType,
    priority: 'medium' as TaskPriority,
    dueDate: '',
    isDeferred: false,
    startDate: '',
  });

  const filteredTasks = tasks.filter(task => {
    if (filter === 'active') {
      return task.status === 'todo';
    }
    if (filter === 'completed') {
      return task.status === 'done';
    }
    return true;
  });

  const activeTasks = tasks.filter(t => t.status === 'todo');
  const completedTasks = tasks.filter(t => t.status === 'done');
  const manualTasks = tasks.filter(t => !t.isAutoGenerated);
  const autoTasks = tasks.filter(t => t.isAutoGenerated);

  const handleOpenCreateDialog = () => {
    setNewTask({
      title: '',
      description: '',
      type: 'general',
      priority: 'medium',
      dueDate: '',
      isDeferred: false,
      startDate: '',
    });
    setCreateDialogOpen(true);
  };

  const handleCreateTask = () => {
    if (!newTask.title.trim()) {
      toast.error('Введите название задачи');
      return;
    }
    if (!newTask.description.trim()) {
      toast.error('Введите описание задачи');
      return;
    }
    if (newTask.isDeferred && !newTask.startDate) {
      toast.error('Укажите дату начала отложенной задачи');
      return;
    }

    if (newTask.isDeferred) {
      toast.success(`Отложенная задача "${newTask.title}" создана! Администратор увидит её ${new Date(newTask.startDate).toLocaleDateString('ru-RU')}`);
    } else {
      toast.success(`Задача "${newTask.title}" создана и назначена администратору!`);
    }
    setCreateDialogOpen(false);
  };

  const handleViewDetails = (task: Task) => {
    setSelectedTask(task);
    setDetailsOpen(true);
  };

  const handleDeleteTask = (task: Task) => {
    if (confirm(`Вы уверены, что хотите удалить задачу "${task.title}"?`)) {
      toast.success(`Задача "${task.title}" удалена`);
      setDetailsOpen(false);
    }
  };

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString('ru-RU', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });
  };

  const formatTime = (date: Date) => {
    return new Date(date).toLocaleTimeString('ru-RU', {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const isOverdue = (task: Task) => {
    if (!task.dueDate || task.status === 'done') return false;
    return new Date(task.dueDate) < new Date();
  };

  const statusConfig = {
    todo: { label: 'К выполнению', icon: Clock, color: 'text-blue-500' },
    done: { label: 'Выполнено', icon: CheckCircle2, color: 'text-green-500' },
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto animate-scale-in">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-[#133C2A] mb-2">Задачи</h1>
          <p className="text-[#133C2A]/60">Управление задачами для администратора</p>
        </div>

        <Button 
          onClick={handleOpenCreateDialog}
          className="rounded-2xl bg-gradient-to-r from-[#133C2A] to-[#D4AF37] hover:opacity-90 gap-2"
        >
          <Plus className="w-5 h-5" />
          Создать задачу
        </Button>
      </div>

      {/* Filters */}
      <div className="flex gap-2">
        <Button
          variant={filter === 'all' ? 'default' : 'outline'}
          onClick={() => setFilter('all')}
          className={`rounded-xl ${
            filter === 'all'
              ? 'bg-gradient-to-r from-[#133C2A] to-[#D4AF37] text-white'
              : 'border-[#133C2A]/20 hover:bg-[#133C2A]/5'
          }`}
        >
          Все ({tasks.length})
        </Button>
        <Button
          variant={filter === 'active' ? 'default' : 'outline'}
          onClick={() => setFilter('active')}
          className={`rounded-xl ${
            filter === 'active'
              ? 'bg-gradient-to-r from-[#133C2A] to-[#D4AF37] text-white'
              : 'border-[#133C2A]/20 hover:bg-[#133C2A]/5'
          }`}
        >
          Активные ({activeTasks.length})
        </Button>
        <Button
          variant={filter === 'completed' ? 'default' : 'outline'}
          onClick={() => setFilter('completed')}
          className={`rounded-xl ${
            filter === 'completed'
              ? 'bg-gradient-to-r from-[#133C2A] to-[#D4AF37] text-white'
              : 'border-[#133C2A]/20 hover:bg-[#133C2A]/5'
          }`}
        >
          Выполнено ({completedTasks.length})
        </Button>
      </div>

      {/* Statistics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="border-none soft-shadow">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[#133C2A]/60">Всего задач</p>
                <p className="text-2xl text-[#133C2A] mt-1">{tasks.length}</p>
              </div>
              <div className="w-12 h-12 rounded-xl bg-[#F8F4E3] flex items-center justify-center">
                <FileText className="w-6 h-6 text-[#D4AF37]" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-none soft-shadow">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[#133C2A]/60">Активные</p>
                <p className="text-2xl text-[#133C2A] mt-1">{activeTasks.length}</p>
              </div>
              <div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center">
                <Clock className="w-6 h-6 text-blue-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-none soft-shadow">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[#133C2A]/60">Созданные</p>
                <p className="text-2xl text-[#133C2A] mt-1">{manualTasks.length}</p>
              </div>
              <div className="w-12 h-12 rounded-xl bg-purple-50 flex items-center justify-center">
                <UserIcon className="w-6 h-6 text-purple-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-none soft-shadow">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[#133C2A]/60">Автоматические</p>
                <p className="text-2xl text-[#133C2A] mt-1">{autoTasks.length}</p>
              </div>
              <div className="w-12 h-12 rounded-xl bg-orange-50 flex items-center justify-center">
                <Settings className="w-6 h-6 text-orange-500" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tasks List */}
      <div className="space-y-4">
        {filteredTasks.length === 0 ? (
          <Card className="border-none soft-shadow">
            <CardContent className="py-12 text-center">
              <FileText className="w-16 h-16 text-[#D4AF37] mx-auto mb-4" />
              <h3 className="text-[#133C2A] mb-2">Нет задач</h3>
              <p className="text-[#133C2A]/60">
                {filter === 'completed' 
                  ? 'Пока нет выполненных задач'
                  : 'Создайте первую задачу для администратора'}
              </p>
            </CardContent>
          </Card>
        ) : (
          filteredTasks.map((task) => {
            const StatusIcon = statusConfig[task.status].icon;
            const TypeIcon = typeConfig[task.type].icon;
            const overdue = isOverdue(task);

            return (
              <Card 
                key={task.id} 
                className={`border-none soft-shadow hover:shadow-lg transition-smooth cursor-pointer ${
                  overdue ? 'ring-2 ring-red-200' : ''
                }`}
                onClick={() => handleViewDetails(task)}
              >
                <CardContent className="p-6">
                  <div className="flex items-start gap-4">
                    {/* Status Icon */}
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${
                      task.status === 'done' ? 'bg-green-50' : 'bg-blue-50'
                    }`}>
                      <StatusIcon className={`w-5 h-5 ${statusConfig[task.status].color}`} />
                    </div>

                    {/* Task Info */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-4 mb-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <h3 className="text-[#133C2A]">{task.title}</h3>
                            {task.isAutoGenerated && (
                              <Badge className="bg-purple-50 text-purple-600 border-purple-200 text-xs">
                                Авто
                              </Badge>
                            )}
                            {task.startDate && new Date(task.startDate) > new Date() && (
                              <Badge className="bg-orange-50 text-orange-600 border-orange-200 text-xs">
                                Отложенная
                              </Badge>
                            )}
                          </div>
                          <p className="text-sm text-[#133C2A]/60 line-clamp-2">{task.description}</p>
                        </div>

                        {/* Priority Badge */}
                        <Badge className={`${priorityConfig[task.priority].bgColor} ${priorityConfig[task.priority].color} border whitespace-nowrap`}>
                          {priorityConfig[task.priority].label}
                        </Badge>
                      </div>

                      {/* Task Meta */}
                      <div className="flex flex-wrap items-center gap-4 text-sm text-[#133C2A]/60">
                        <div className="flex items-center gap-1">
                          <TypeIcon className="w-4 h-4" />
                          <span>{typeConfig[task.type].label}</span>
                        </div>

                        <div className="flex items-center gap-1">
                          <Badge className={`text-xs ${
                            task.status === 'done' ? 'bg-green-50 text-green-600 border-green-200' :
                            'bg-blue-50 text-blue-600 border-blue-200'
                          }`}>
                            {statusConfig[task.status].label}
                          </Badge>
                        </div>

                        {task.dueDate && (
                          <div className={`flex items-center gap-1 ${overdue ? 'text-red-500' : ''}`}>
                            <Calendar className="w-4 h-4" />
                            <span>{formatDate(task.dueDate)}</span>
                            {overdue && <AlertCircle className="w-4 h-4" />}
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Actions */}
                    {!task.isAutoGenerated && (
                      <div className="flex gap-1 flex-shrink-0">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDeleteTask(task);
                          }}
                          className="w-8 h-8 p-0 rounded-xl hover:bg-red-50"
                        >
                          <Trash2 className="w-4 h-4 text-red-500" />
                        </Button>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })
        )}
      </div>

      {/* Create Task Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle className="text-[#133C2A]">Создать новую задачу</DialogTitle>
            <DialogDescription>
              Задача будет назначена администратору
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="title" className="text-[#133C2A]">
                Название задачи <span className="text-red-500">*</span>
              </Label>
              <Input
                id="title"
                value={newTask.title}
                onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                placeholder="Например: Связаться с родителями группы Начинающие"
                className="rounded-xl border-[#133C2A]/20 focus:border-[#D4AF37]"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="description" className="text-[#133C2A]">
                Описание <span className="text-red-500">*</span>
              </Label>
              <textarea
                id="description"
                value={newTask.description}
                onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                placeholder="Подробное описание задачи..."
                className="w-full min-h-[120px] px-3 py-2 rounded-xl border border-[#133C2A]/20 bg-white text-[#133C2A] focus:border-[#D4AF37] focus:ring-2 focus:ring-[#D4AF37]/20 outline-none resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="type" className="text-[#133C2A]">
                  Тип задачи
                </Label>
                <div className="relative">
                  <select
                    id="type"
                    value={newTask.type}
                    onChange={(e) => setNewTask({ ...newTask, type: e.target.value as TaskType })}
                    className="w-full h-10 px-3 pr-10 rounded-xl border border-[#133C2A]/20 bg-white text-[#133C2A] focus:border-[#D4AF37] focus:ring-2 focus:ring-[#D4AF37]/20 outline-none appearance-none cursor-pointer"
                  >
                    {Object.entries(typeConfig).map(([value, config]) => (
                      <option key={value} value={value}>
                        {config.label}
                      </option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-[#133C2A]/50 pointer-events-none" />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="priority" className="text-[#133C2A]">
                  Приоритет
                </Label>
                <div className="relative">
                  <select
                    id="priority"
                    value={newTask.priority}
                    onChange={(e) => setNewTask({ ...newTask, priority: e.target.value as TaskPriority })}
                    className="w-full h-10 px-3 pr-10 rounded-xl border border-[#133C2A]/20 bg-white text-[#133C2A] focus:border-[#D4AF37] focus:ring-2 focus:ring-[#D4AF37]/20 outline-none appearance-none cursor-pointer"
                  >
                    {Object.entries(priorityConfig).map(([value, config]) => (
                      <option key={value} value={value}>
                        {config.label}
                      </option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-[#133C2A]/50 pointer-events-none" />
                </div>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="dueDate" className="text-[#133C2A]">
                Срок выполнения
              </Label>
              <Input
                id="dueDate"
                type="date"
                value={newTask.dueDate}
                onChange={(e) => setNewTask({ ...newTask, dueDate: e.target.value })}
                className="rounded-xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                min={new Date().toISOString().split('T')[0]}
              />
            </div>

            {/* Отложенная задача */}
            <div className="space-y-3 p-4 rounded-xl bg-[#F8F4E3] border border-[#133C2A]/10">
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  id="isDeferred"
                  checked={newTask.isDeferred}
                  onChange={(e) => setNewTask({ ...newTask, isDeferred: e.target.checked, startDate: e.target.checked ? newTask.startDate : '' })}
                  className="w-5 h-5 rounded border-[#133C2A]/20 text-[#D4AF37] focus:ring-[#D4AF37] cursor-pointer"
                />
                <div className="flex-1">
                  <Label htmlFor="isDeferred" className="text-[#133C2A] cursor-pointer">
                    Отложенная задача
                  </Label>
                  <p className="text-xs text-[#133C2A]/60 mt-0.5">
                    Задача будет показана администратору только в указанную дату
                  </p>
                </div>
              </div>

              {newTask.isDeferred && (
                <div className="space-y-2 pt-2 border-t border-[#133C2A]/10">
                  <Label htmlFor="startDate" className="text-[#133C2A]">
                    Дата начала задачи <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="startDate"
                    type="date"
                    value={newTask.startDate}
                    onChange={(e) => setNewTask({ ...newTask, startDate: e.target.value })}
                    className="rounded-xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                    min={new Date().toISOString().split('T')[0]}
                  />
                  <p className="text-xs text-[#133C2A]/60">
                    До этой даты задача будет скрыта от администратора
                  </p>
                </div>
              )}
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setCreateDialogOpen(false)}
              className="border-[#133C2A]/20 hover:bg-[#133C2A]/5 rounded-xl"
            >
              Отмена
            </Button>
            <Button
              onClick={handleCreateTask}
              className="bg-gradient-to-r from-[#133C2A] to-[#D4AF37] text-white hover:opacity-90 rounded-xl"
            >
              Создать задачу
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Task Details Dialog */}
      {selectedTask && (
        <Dialog open={detailsOpen} onOpenChange={setDetailsOpen}>
          <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <DialogTitle className="text-[#133C2A] text-xl mb-2">
                    {selectedTask.title}
                  </DialogTitle>
                  <div className="flex gap-2">
                    <Badge className={`${priorityConfig[selectedTask.priority].bgColor} ${priorityConfig[selectedTask.priority].color} border`}>
                      {priorityConfig[selectedTask.priority].label}
                    </Badge>
                    <Badge className="bg-[#F8F4E3] text-[#133C2A] border-[#133C2A]/20">
                      {statusConfig[selectedTask.status].label}
                    </Badge>
                    {selectedTask.isAutoGenerated && (
                      <Badge className="bg-purple-50 text-purple-600 border-purple-200">
                        Автоматическая
                      </Badge>
                    )}
                  </div>
                </div>
              </div>
            </DialogHeader>

            <div className="space-y-4 py-4">
              {/* Description */}
              <div>
                <h4 className="text-sm text-[#133C2A] mb-2">Описание</h4>
                <p className="text-sm text-[#133C2A]/70 bg-[#F8F4E3] p-4 rounded-xl">
                  {selectedTask.description}
                </p>
              </div>

              {/* Task Info */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <p className="text-xs text-[#133C2A]/60">Тип задачи</p>
                  <p className="text-sm text-[#133C2A]">{typeConfig[selectedTask.type].label}</p>
                </div>

                <div className="space-y-1">
                  <p className="text-xs text-[#133C2A]/60">Создано</p>
                  <p className="text-sm text-[#133C2A]">
                    {formatDate(selectedTask.createdAt)} в {formatTime(selectedTask.createdAt)}
                  </p>
                </div>

                {selectedTask.startDate && (
                  <div className="space-y-1">
                    <p className="text-xs text-[#133C2A]/60">Дата начала</p>
                    <p className={`text-sm ${new Date(selectedTask.startDate) > new Date() ? 'text-orange-600' : 'text-[#133C2A]'}`}>
                      {formatDate(selectedTask.startDate)}
                      {new Date(selectedTask.startDate) > new Date() && ' (Отложенная)'}
                    </p>
                  </div>
                )}

                {selectedTask.dueDate && (
                  <div className="space-y-1">
                    <p className="text-xs text-[#133C2A]/60">Срок выполнения</p>
                    <p className={`text-sm ${isOverdue(selectedTask) ? 'text-red-500' : 'text-[#133C2A]'}`}>
                      {formatDate(selectedTask.dueDate)}
                      {isOverdue(selectedTask) && ' (Просрочено)'}
                    </p>
                  </div>
                )}

                {selectedTask.completedAt && (
                  <div className="space-y-1">
                    <p className="text-xs text-[#133C2A]/60">Выполнено</p>
                    <p className="text-sm text-green-600">
                      {formatDate(selectedTask.completedAt)} в {formatTime(selectedTask.completedAt)}
                    </p>
                  </div>
                )}
              </div>
            </div>

            <DialogFooter>
              {!selectedTask.isAutoGenerated && (
                <Button
                  variant="outline"
                  onClick={() => handleDeleteTask(selectedTask)}
                  className="border-red-200 text-red-600 hover:bg-red-50 rounded-xl"
                >
                  <Trash2 className="w-4 h-4 mr-2" />
                  Удалить задачу
                </Button>
              )}
              <Button
                variant="outline"
                onClick={() => setDetailsOpen(false)}
                className="border-[#133C2A]/20 hover:bg-[#133C2A]/5 rounded-xl"
              >
                Закрыть
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}