server {
    listen 80;
    server_name manera.hyperconnect.fun;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://maneradancestudio.ru$request_uri;
    }
}

server {
    listen 80;
    server_name maneradancestudio.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /opt/manera-crm/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
