import { useState, useEffect } from 'react';
import { Calendar, Send, CheckCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { toast } from 'sonner@2.0.3';
import { Task, Notification } from '../types';

interface TrialClassDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onAddTask: (task: Task) => void;
  onAddNotification: (notification: Notification) => void;
}

export function TrialClassDialog({ isOpen, onClose, onAddTask, onAddNotification }: TrialClassDialogProps) {
  const [formData, setFormData] = useState({
    childName: '',
    childBirthDate: '',
    previousExperience: '',
    parentName: '',
    parentPhone: '',
    healthRestrictions: '',
    howDidYouKnow: '',
  });

  const [showSuccessDialog, setShowSuccessDialog] = useState(false);

  // Функция для расчета возраста из даты рождения
  const calculateAge = (birthDate: string): number => {
    if (!birthDate) return 0;
    const today = new Date();
    const birth = new Date(birthDate);
    let age = today.getFullYear() - birth.getFullYear();
    const monthDiff = today.getMonth() - birth.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
      age--;
    }
    return age;
  };

  // Автоматическое закрытие диалога успеха через 5 секунд
  useEffect(() => {
    if (showSuccessDialog) {
      const timer = setTimeout(() => {
        setShowSuccessDialog(false);
        onClose();
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [showSuccessDialog, onClose]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Валидация обязательных полей
    if (!formData.childName || !formData.childBirthDate || !formData.previousExperience || !formData.parentName || !formData.parentPhone || !formData.howDidYouKnow) {
      toast.error('Пожалуйста, заполните все обязательные поля');
      return;
    }

    const age = calculateAge(formData.childBirthDate);

    // Создание срочной задачи для администратора
    const newTask: Task = {
      id: `trial-${Date.now()}`,
      title: 'Обработать заявку на пробное занятие',
      description: `Связаться с родителем и назначить дату пробного занятия.\n\nРебенок: ${formData.childName}, ${age} ${age === 1 ? 'год' : age >= 2 && age <= 4 ? 'года' : 'лет'}\nРодитель: ${formData.parentName}\nТелефон: ${formData.parentPhone}\nОпыт: ${formData.previousExperience}\n${formData.healthRestrictions ? `Ограничения: ${formData.healthRestrictions}` : ''}\nИсточник: ${formData.howDidYouKnow}`,
      type: 'communication',
      priority: 'urgent',
      status: 'todo',
      assigneeId: '3', // ID администратора (Мария Иванова из моковых данных)
      assigneeName: 'Мария Иванова',
      createdBy: 'system',
      createdByName: 'Система',
      createdAt: new Date(),
      dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000), // Через 24 часа
      relatedUserName: formData.parentName,
      isAutoGenerated: true,
      notes: `Заявка получена через форму на сайте`,
    };
    onAddTask(newTask);

    // Создание уведомления для админа и владельца
    const newNotification: Notification = {
      id: `notif-${Date.now()}`,
      type: 'trial_class',
      priority: 'high',
      title: 'Новая заявка на пробное занятие',
      message: `${formData.childName}, ${age} ${age === 1 ? 'год' : age >= 2 && age <= 4 ? 'года' : 'лет'}`,
      additionalInfo: formData.previousExperience,
      highlightedData: {
        parentName: formData.parentName,
        parentPhone: formData.parentPhone,
      },
      createdAt: new Date(),
      forRoles: ['admin', 'owner'],
      metadata: formData,
    };
    onAddNotification(newNotification);

    // Показать диалог успеха
    setShowSuccessDialog(true);
    
    // Сброс формы
    setFormData({
      childName: '',
      childBirthDate: '',
      previousExperience: '',
      parentName: '',
      parentPhone: '',
      healthRestrictions: '',
      howDidYouKnow: '',
    });
  };

  return (
    <>
      <Dialog open={isOpen && !showSuccessDialog} onOpenChange={onClose}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl">
          <DialogHeader>
            <DialogTitle className="text-[#133C2A] flex items-center gap-2">
              <Calendar className="w-5 h-5" />
              Записаться на пробное занятие
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-6 py-4">
            {/* Информация о ребенке */}
            <div className="space-y-4">
              <h3 className="text-[#133C2A]">Информация о ребенке</h3>
              
              {/* ФИО ребенка */}
              <div className="space-y-2">
                <Label htmlFor="childName" className="text-[#133C2A]">
                  ФИО ребенка <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="childName"
                  value={formData.childName}
                  onChange={(e) => setFormData({ ...formData, childName: e.target.value })}
                  placeholder="Иванова Мария Александровна"
                  required
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                />
              </div>

              {/* Дата рождения */}
              <div className="space-y-2">
                <Label htmlFor="childBirthDate" className="text-[#133C2A]">
                  Дата рождения <span className="text-red-500">*</span>
                  {formData.childBirthDate && (
                    <span className="text-[#D4AF37] ml-2">
                      (возраст: {calculateAge(formData.childBirthDate)} {calculateAge(formData.childBirthDate) === 1 ? 'год' : calculateAge(formData.childBirthDate) >= 2 && calculateAge(formData.childBirthDate) <= 4 ? 'года' : 'лет'})
                    </span>
                  )}
                </Label>
                <Input
                  id="childBirthDate"
                  type="date"
                  value={formData.childBirthDate}
                  onChange={(e) => setFormData({ ...formData, childBirthDate: e.target.value })}
                  required
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                />
              </div>

              {/* Предыдущий опыт */}
              <div className="space-y-2">
                <Label htmlFor="previousExperience" className="text-[#133C2A]">
                  Где и чем занимался ранее <span className="text-red-500">*</span>
                </Label>
                <Textarea
                  id="previousExperience"
                  value={formData.previousExperience}
                  onChange={(e) => setFormData({ ...formData, previousExperience: e.target.value })}
                  placeholder="Например: 2 года в хореографической студии, занимался гимнастикой"
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37] min-h-[80px]"
                />
              </div>

              {/* Ограничения по здоровью */}
              <div className="space-y-2">
                <Label htmlFor="healthRestrictions" className="text-[#133C2A]">
                  Ограничения по здоровью
                </Label>
                <Textarea
                  id="healthRestrictions"
                  value={formData.healthRestrictions}
                  onChange={(e) => setFormData({ ...formData, healthRestrictions: e.target.value })}
                  placeholder="Укажите, если есть какие-либо медицинские ограничения"
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37] min-h-[80px]"
                />
              </div>
            </div>

            {/* Информация о родителе */}
            <div className="space-y-4 pt-4 border-t border-[#133C2A]/10">
              <h3 className="text-[#133C2A]">Контактные данные родителя</h3>
              
              {/* ФИО родителя */}
              <div className="space-y-2">
                <Label htmlFor="parentName" className="text-[#133C2A]">
                  ФИО родителя <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="parentName"
                  value={formData.parentName}
                  onChange={(e) => setFormData({ ...formData, parentName: e.target.value })}
                  placeholder="Иванова Мария Петровна"
                  required
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                />
              </div>

              {/* Телефон родителя */}
              <div className="space-y-2">
                <Label htmlFor="parentPhone" className="text-[#133C2A]">
                  Номер телефона родителя <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="parentPhone"
                  type="tel"
                  value={formData.parentPhone}
                  onChange={(e) => setFormData({ ...formData, parentPhone: e.target.value })}
                  placeholder="+7 (999) 123-45-67"
                  required
                  className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37]"
                />
              </div>
            </div>

            {/* Откуда узнали */}
            <div className="space-y-2 pt-4 border-t border-[#133C2A]/10">
              <Label htmlFor="howDidYouKnow" className="text-[#133C2A]">
                Откуда узнали о нас? <span className="text-red-500">*</span>
              </Label>
              <Select
                value={formData.howDidYouKnow}
                onValueChange={(value) => setFormData({ ...formData, howDidYouKnow: value })}
                required
              >
                <SelectTrigger className="rounded-2xl border-[#133C2A]/20 focus:border-[#D4AF37]">
                  <SelectValue placeholder="Выберите вариант" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="instagram">Instagram</SelectItem>
                  <SelectItem value="facebook">Facebook</SelectItem>
                  <SelectItem value="vk">VK</SelectItem>
                  <SelectItem value="friends">От друзей/знакомых</SelectItem>
                  <SelectItem value="search">Поисковая система</SelectItem>
                  <SelectItem value="advertisement">Реклама</SelectItem>
                  <SelectItem value="passedby">Проходили мимо</SelectItem>
                  <SelectItem value="other">Другое</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Кнопки */}
            <div className="flex gap-3 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="flex-1 rounded-2xl border-[#133C2A]/20"
              >
                Отмена
              </Button>
              <Button
                type="submit"
                className="flex-1 rounded-2xl bg-gradient-to-r from-[#133C2A] to-[#D4AF37] hover:opacity-90 gap-2"
              >
                <Send className="w-4 h-4" />
                Отправить заявку
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {/* Диалог успешной отправки */}
      <Dialog open={showSuccessDialog} onOpenChange={() => setShowSuccessDialog(false)}>
        <DialogContent className="max-w-md rounded-3xl">
          <div className="flex flex-col items-center justify-center py-8 px-4 text-center">
            <div className="w-20 h-20 rounded-full bg-gradient-to-r from-[#133C2A] to-[#D4AF37] flex items-center justify-center mb-6">
              <CheckCircle className="w-12 h-12 text-white" />
            </div>
            <h2 className="text-[#133C2A] text-2xl mb-3">
              Спасибо за вашу заявку!
            </h2>
            <p className="text-[#133C2A]/70 mb-6">
              Мы получили вашу заявку на пробное занятие. Наш менеджер свяжется с вами в ближайшее время для подтверждения записи.
            </p>
            <div className="w-full bg-[#F8F4E3] rounded-full h-1 overflow-hidden">
              <div 
                className="h-full bg-gradient-to-r from-[#133C2A] to-[#D4AF37] animate-[shrink_5s_linear]"
                style={{
                  animation: 'shrink 5s linear',
                }}
              />
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <style>{`
        @keyframes shrink {
          from {
            width: 100%;
          }
          to {
            width: 0%;
          }
        }
      `}</style>
    </>
  );
}